apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: inventory
type: Opaque
data:
  hosts: QkFTRTY0RU5DT0RFRF9QUk9WSURFUl9DUkVEUw==
---
apiVersion: ansible.m.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: secret-inventory-remote-debug
  namespace: default
spec:
  forProvider:
    inventories:
      - source: Secret
        secretRef:
          namespace: default
          name: inventory
          key: hosts
    playbookInline: |
      ---
      - hosts: all
        tasks:
          - name: ansibleplaybook-simple
            debug:
              msg: Your are running 'ansibleplaybook-simple' example
